In [1]:
import numpy as np

In [2]:
lst = [[1,3,5],[2,4,6]]

In [3]:
print(type(lst))

<class 'list'>


In [4]:
np_list = np.array(lst)

In [6]:
print(type(np_list))

<class 'numpy.ndarray'>


In [8]:
np.array(lst, dtype=np.float)

array([[1., 3., 5.],
       [2., 4., 6.]])

In [11]:
print(np_list.dtype)

int64


In [12]:
print(np_list.itemsize)

8


In [13]:
print(np_list.size)

6


In [14]:
print(np_list.shape)

(2, 3)


In [15]:
print(np_list.ndim)

2


In [16]:
# Some Arrays

In [17]:
print(np.zeros([2,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
print("Rand:")

Rand:


In [19]:
print(np.random.rand(2,4))

[[0.53596796 0.32767676 0.28809832 0.06490666]
 [0.85474654 0.6369061  0.99028423 0.89809447]]


In [20]:
print(np.random.rand())

0.2101375602542923


In [21]:
print(np.random.randint(1,10,3))

[7 2 7]


In [22]:
print(np.random.randn(2,4))

[[-1.25874806  0.45747587 -2.0885859  -1.50230519]
 [-0.34973978 -0.53684505  0.22884624  0.82001297]]


In [24]:
print(np.random.choice([10,20,30]))

30


In [27]:
print(np.random.beta(1,10,10))

[0.05595644 0.08651968 0.06534471 0.03811193 0.00344379 0.17322846
 0.02481048 0.01810955 0.01948326 0.20223532]


In [28]:
# Array Opes

In [29]:
lst = np.arange(1,11).reshape([2,-1])

In [30]:
lst

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
np.exp(lst)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [32]:
np.exp2(lst)

array([[   2.,    4.,    8.,   16.,   32.],
       [  64.,  128.,  256.,  512., 1024.]])

In [33]:
np.sqrt(lst)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [34]:
np.sin(lst)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [35]:
np.log(lst)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [38]:
lst=np.arange(1,21).reshape([5,-1])

In [40]:
lst

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [41]:
lst.sum(axis=0)

array([45, 50, 55, 60])

In [42]:
lst.sum(axis=1)

array([10, 26, 42, 58, 74])

In [49]:
lst = np.array([[[1, 2, 3, 4],[4, 5, 6, 7]], [[7, 8, 9, 10], [10, 11, 12, 13]]])

In [50]:
lst

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7]],

       [[ 7,  8,  9, 10],
        [10, 11, 12, 13]]])

In [51]:
lst.sum(axis=0)

array([[ 8, 10, 12, 14],
       [14, 16, 18, 20]])

In [52]:
lst.sum(axis=1)

array([[ 5,  7,  9, 11],
       [17, 19, 21, 23]])

In [53]:
lst.sum(axis=2)

array([[10, 22],
       [34, 46]])

In [54]:
lst.sum()

112

In [56]:
lst.min(axis=1)

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [57]:
lst.max(axis=2)

array([[ 4,  7],
       [10, 13]])

In [58]:
lst1 = np.array([10, 20, 30, 40])
lst2 = np.array([4, 3, 2, 1])

In [59]:
lst1+lst2

array([14, 23, 32, 41])

In [60]:
lst1-lst2

array([ 6, 17, 28, 39])

In [61]:
lst1**2

array([ 100,  400,  900, 1600])

In [62]:
np.dot(lst1.reshape([2,2]), lst2.reshape([2,2]))

array([[ 80,  50],
       [200, 130]])

In [63]:
np.concatenate((lst1, lst2), axis=0)

array([10, 20, 30, 40,  4,  3,  2,  1])

In [66]:
np.vstack((lst1, lst2))

array([[10, 20, 30, 40],
       [ 4,  3,  2,  1]])

In [67]:
np.hstack((lst1, lst2))

array([10, 20, 30, 40,  4,  3,  2,  1])

In [68]:
np.split(lst1, 2)

[array([10, 20]), array([30, 40])]

In [69]:
np.copy(lst1)

array([10, 20, 30, 40])

In [70]:
# Liner

In [71]:
from numpy.linalg import *

In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
lst = np.array([[1, 2.], [3, 4.]])

In [74]:
lst

array([[1., 2.],
       [3., 4.]])

In [75]:
inv(lst)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [76]:
lst.transpose()

array([[1., 3.],
       [2., 4.]])

In [77]:
det(lst)

-2.0000000000000004

In [78]:
eig(lst)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [79]:
y = np.array([[5.],[7.]])

In [80]:
solve(lst, y)

array([[-3.],
       [ 4.]])

In [81]:
# FFT

In [82]:
np.fft.fft(np.array(np.ones(8)))

array([8.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [83]:
np.corrcoef([1, 0, 1], [0, 2, 1])

array([[ 1.       , -0.8660254],
       [-0.8660254,  1.       ]])

In [85]:
np.poly([2, 1, 3])

array([ 1., -6., 11., -6.])